### ISSUE TITLE
Bad UI rendering

### ISSUE THREAD

**Issue by ioanachelaru** [githubuser0xFFFF/Qt-Advanced-Docking-System#386] opened 2021-12-16 12:44 UTC
I am having some trouble with the UI rendering when a widget is detached, the main window is being minimized and then maximized again. It is a pretty big project with lots of hidden layouts and widgets, and when the window is being maximized all of those hidden items get mixed up and appear. 
Also, it seems that after the maximization, the floating window containing the `DockWidget` doesn't appear anymore. I found that the same thing happens in the `SimpleExample` project.  I enabled the debug prints and I see that for both my project and the example this message is shown, right after the detaching event:
```
CFloatingDockContainer::onDockAreasAddedOrRemoved()
ATOM TYPE MISMATCH ( _NET_WM_STATE ). Expected:  4   but got  0
```

Is this a known bug or is there anything I can do about it?
Thanks in advance.

**Comment by githubuser0xFFFF** [comment] 2021-12-16 13:32
I just tested the simple example and it works. What are the steps I need to do, to see this issue?

**Comment by ioanachelaru** [comment] 2021-12-17 13:08
I did some more testing and I cannot reproduce the issue in a simpler app. In my project, what I did was simply create a manager, add it to a layout, add a dock widget to it and the issue appeared. I am inclined to believe that there might be something related to me using qwt plots, perhaps a memory leak or something that gets deleted too soon. I'll get back when I have an exact answer to it.

**Comment by githubuser0xFFFF** [comment] 2021-12-17 13:39
Ok, thank you. I will close the issue for now. In case of a problem I need a small test case to reproduce the issue because I can only fix it if I can reproduce it.

**Closed by githubuser0xFFFF** 2021-12-17 13:39 UTC

**Comment by ioanachelaru** [comment] 2021-12-21 16:19
I did manage to find the bug here, it was something on my side, some widgets weren't explicitly hidden and the paint events from the library interfered with that. Sorry for the spam.
