### ISSUE TITLE
PyPI package needs updates

### ISSUE THREAD

**Issue by nateskulic** [githubuser0xFFFF/Qt-Advanced-Docking-System#595] opened 2024-01-03 13:07 UTC
Hi!

The package on [PyPI](https://pypi.org/project/PyQtAds) is quite outdated (3.8.1) and there is a limited selection of wheels. 

How can we get it updated? Does anyone here have access?

Thanks!

**Comment by githubuser0xFFFF** [comment] 2024-01-04 06:27
Duplicate of #575

**Closed by githubuser0xFFFF** 2024-01-04 06:27 UTC
Labels: help wanted, python
