### ISSUE TITLE
Qt 5.14 - 5.15: Not all floating widgets close when close button in main window clicked

### ISSUE THREAD

**Issue by cywsnlam** [githubuser0xFFFF/Qt-Advanced-Docking-System#224] opened 2020-07-16 03:28 UTC
Hi, 
    When I start the demo app in Qt Creator in MacOS (Catalina) platform, with two or more floating widgets present, and the close button of main window clicked, just one floating widget and the main window close and the rest of other floating widgets remain and the app does not terminate as desired.
Please confirm this issue. 

The package version is 3.5.2.

Thank you.

**Comment by githubuser0xFFFF** [comment] 2020-07-16 07:32
I just tested this on Windows and Linux and cannot confirm this problem. Maybe someone with a Mac can help. I do not have one - sorry.

**Comment by SleepProgger** [comment] 2020-07-21 16:11
Can confirm on linux with QT 5.14.2. With the demo when there is more than one floating window open closing the application only will close one.

A quick workaround is to add `delete d->DockManager;` in the demos `CMainWindow::closeEvent` function.
DockManagers destructor removes all floating windows.

This is likely not the proper solution tho.

**Comment by githubuser0xFFFF** [comment] 2020-07-21 20:49
I tested this with the following setups:

- Ubuntu 20.04 with Qt 5.12.8
- Ubuntu 18.04 with Qt 5.9.5

and could not reproduce the problem. So at the moment it seems to be a Qt 5.14.2 related issue.

**Comment by SleepProgger** [comment] 2020-07-21 21:42
After some bisecting.
NOT affected QT version i tested : 5.12.5 - 5.13.2
Affected 5.14.0 - 5.15.0

So something that changed in 5.14 it seems.

**Comment by githubuser0xFFFF** [comment] 2020-07-22 09:32
@SleepProgger Thank you for testing. I could also reproduce the problem with Qt 5.15 on Windows. The fix is indeed to delete the DockManager in the close event handler of the QMainWindow. This ensures, that all floating DockWidgets are properly "closed" (destroyed) - even floating DockWidgets that are not closable. I updated all demo applications to delete the DockManager in the close event - see commit 4a6d2d3514815ebdfd8857e6551919c25d3ea69c

**Closed by githubuser0xFFFF** 2020-07-22 09:32 UTC
Labels: help wanted, under review

**Comment by rolivav** [comment] 2020-07-23 08:57
I still don't understand how this could happen, isn't the main window the parent of the CDockManager?

**Comment by githubuser0xFFFF** [comment] 2020-07-23 09:07
Yes, this is right. The CDockManager is a child of the main window.

**Comment by rolivav** [comment] 2020-07-23 09:42
Shouldn't all the windows be deleted when the main window is destroyed then? They should all be children of the main window. I think there is something strange going on.

**Comment by githubuser0xFFFF** [comment] 2020-07-23 09:47
Yes, you are right and they will be destroyed. So do you know when the MainWindow will be destroyed?

**Comment by rolivav** [comment] 2020-07-23 10:18
Aaaah I see 😄 I guess it would also be fixed if you set `Qt::WA_DeleteOnClose` on the QMainWindow and create it dynamically.
Anyway that makes sense, thanks for explaining 👍
