### ISSUE TITLE
Main window becomes black while moving a dockable window (only on i3wm or over x2go remote session)

### ISSUE THREAD

**Issue by LakeFusion** [githubuser0xFFFF/Qt-Advanced-Docking-System#485] opened 2023-02-16 20:21 UTC
Bug Report:

OS: Debian Bullseye
Desktop Client: i3wm or xfce over x2go
Windowing System: X11
Compiler: GCC v10.2.1
Build System: CMake
Tag: 4.0.2

Moving a dockable window results in black main window like in the following screenshot.

![image](https://user-images.githubusercontent.com/96486166/219456548-590bed2c-bda5-4558-9684-7c7335263b7b.png)

So far I've tried it on the same machine locally with the following:
Gnome: Works as expected
Gnome on Xorg: Works as expected
Xfce: Works as expected
i3wm: Issue occurs

However, the same issue also occurs when I connect to another machine (running Ubuntu 22.04.1 LTS with Xfce) over x2go.

Steps to Reproduce:
start the application in i3wm
Undock window from main window

**Comment by githubuser0xFFFF** [comment] 2023-02-16 20:32
Thank you for this bug report but Debian Bullseye is not  a supported platform of ADS.

ADS only supports Windows, MacOS and Ubuntu 18.04, 20.04 and 22.04.

**Comment by LakeFusion** [comment] 2023-02-16 20:37
As I've already included in the details, the issue occurs also on Ubuntu 20.04 while connecting over X2go

**Comment by githubuser0xFFFF** [comment] 2023-02-16 23:54
X2go is not supported. If I test in normal Ubuntu 20.04 I can not reproduce the issue.

**Comment by githubuser0xFFFF** [comment] 2023-02-17 06:45
I think this is more likely a Qt issue and you should file a but report in the Qt issue tracker. ADS only uses standard Qt features so there is nothing I can do to fix this.

**Comment by LakeFusion** [comment] 2023-02-17 09:21
Thanks for testing. Have you tried it with i3wm on Ubuntu? Because GNOME and Xfce are also fine on Debian. Standard QT docking doesn't have this issue. Also the alternative docking system you've mentioned on your website https://github.com/KestrelRadarSensors/dockingpanes works fine as well. Therefore I really doubt that this is a QT issue.

**Comment by githubuser0xFFFF** [comment] 2023-02-17 19:05
I reopened the issue and assigned it to you. Would be great if you could find out, why it works in the other project and not in ADS.

**Comment by mrdeveloperdude** [comment] 2023-03-17 16:43
I just built ADS for the first time from source using official Qt6.4.2 and see the same issue. I understand that since I am on Debian and since ADS only supports Ubuntu that this will probably not be resolved. Too bad, seemed like a promising feature to include in my app. Sayonara!

**Comment by clickingbuttons** [comment] 2023-03-28 21:12
The issue is Qt6 vs Qt5. There's the same regression with https://github.com/KDAB/KDDockWidgets as well on both their `1.7` and `2.0` branches.
![image](https://user-images.githubusercontent.com/43246297/228367135-5b23f325-6fc5-467b-8890-a584f4e2d396.png)

The issue still exists in the https://github.com/KestrelRadarSensors/dockingpanes project the OP mentioned, even though that uses Qt5. It just looks better since the drop location indicator doesn't take up the entire window so the black background doesn't look so bad (which is one option to solve it).
![image](https://user-images.githubusercontent.com/43246297/228367730-c2cdd85c-3fd6-47b1-8c98-7dd91c3d0737.png)


I'm investigating now since I'd like to use ONLY Qt6 in my project instead of Qt5. Any pointers would be appreciated.

**Comment by clickingbuttons** [comment] 2023-03-28 23:30
Looks like `setAttribute(Qt::WA_TranslucentBackground);` isn't working.

Related:
https://forum.qt.io/topic/143286/translucent-background-not-rendering-correctly-in-qt6-with-hardware-rendering-but-works-with-software-rendering
https://bugreports.qt.io/browse/QTBUG-69585

**Comment by clickingbuttons** [comment] 2023-03-29 04:02
I compared against https://doc.qt.io/qt-6/qtwidgets-widgets-shapedclock-example.html which works.

It turns out this method is what prevents the black background (which seems like a Qt regression):
```cpp
void ShapedClock::resizeEvent(QResizeEvent * /* event */)
{
    int side = qMin(width(), height());
    QRegion maskedRegion(width() / 2 - side / 2, height() / 2 - side / 2, side,
                         side, QRegion::Ellipse);
    setMask(maskedRegion);
}
```

It doesn't allow for transparency in your image, but it sure is better than a black background.

**Comment by githubuser0xFFFF** [comment] 2023-03-29 12:17
@clickingbuttons Thank you for your comprehensive testing. With this information I could try to fix the issue. The problem is, that I do not have a setup to test this. Is there an easy way in a vanilla Ubuntu 20.04 installation to change the compositior or to set some sort of flag to see the issue?

**Comment by clickingbuttons** [comment] 2023-03-29 19:09
I think the easiest way to test is to just comment out all the `setAttribute(Qt::WA_TranslucentBackground);` and `setAttribute(Qt::WA_NoSystemBackground);`. Without a compositor those calls do nothing.

I'll fire up a Ubuntu VM and look for an option to disable Gnome's default compositor.

**Comment by Tectu** [comment] 2023-09-22 15:47
I am also running into this issue using bspwm as a window manager.

**Comment by githubuser0xFFFF** [comment] 2023-09-22 18:00
I hope someone will fix this soon. Fortunately our Application runs on Windows and I do not see all the Linux  related Qt issues :O)

**Comment by Tectu** [comment] 2023-09-22 21:40
I'd gladly look into this. It's really just a time issue on my end.
I wonder whether this issue is (partly) related to #451. The particular issue on #451 is not apparent anymore as of `4.1.1` but I do also get the black Window.

As you stated in the other issue: Linux is quite a mess indeed. But there are other operating systems such as FreeBSD where we observe the same bug.

**Comment by githubuser0xFFFF** [comment] 2023-09-23 05:45
Maybe you can have a look into KDockWidgets and check, if they have the same problem. If KDockWidgets works, then they may have solved the problem in their code and we can have some "inspiration"

**Comment by githubuser0xFFFF** [comment] 2024-04-04 12:11
If nobody cares about an issue, that it isn't an issue.

**Closed by githubuser0xFFFF** 2024-04-04 12:11 UTC
Labels: help wanted, Linux

**Comment by Tectu** [comment] 2024-04-04 22:03
Sorry about the silence - I very much care about the issue. Won't be able to tackle this until summer tho :/

I'll report back here if/when I get to it.

**Comment by githubuser0xFFFF** [comment] 2024-04-05 09:27
Ok, I will keep the issue closed, because your Linux distribution / configuration is not officially supported by ADS - so I'm afraid you are on your own.

**Comment by Tectu** [comment] 2024-04-05 14:43
That is completely fine & understandable!

**Comment by Tectu** [comment] 2024-06-26 17:51
This is most likely the same issue as #95
