### ISSUE TITLE
macOS: When a window is obscured do not show its docking icons.

### ISSUE THREAD

**Issue by ARSanderson** [githubuser0xFFFF/Qt-Advanced-Docking-System#439] opened 2022-07-14 19:01 UTC
When a window is obscured do not show its docking icons. I have a case where the parent ADS window is fully obscuring a sub ADS window. I have third ADS child window that I want to dock into the parent window. 

Issue, when I move the child window over the parent window depending on the cursor location the docking icons for obscured sub ADS window will show up which is confusing. The first time it happened I could not figure out what happened to the child window as it was docked to the obscured sub window rather than the  parent and thus it too became obscured.

In some cases it prevents one from docking to the parent window because as one gets near the parent's side dock icon the sub window's dock icons appear. As a result one needs to move parent window so not to be near the sub window.

In doing some research I *think* a possible solution would be to first check the window's visible region: https://doc.qt.io/qt-6/qwidget.html#visibleRegion

https://www.qtcentre.org/threads/56573-Get-the-Window-Visible-State-when-it-is-partially-visible

If the region is empty the docking icons are not shown. If the region is fully visible then icons are shown. Though if partially visible one may or may not want to show the docking icons. A case can be made for both.

**Comment by githubuser0xFFFF** [comment] 2022-07-18 05:14
Could you please provide a small minimum sample application that shows the problem?

**Comment by ARSanderson** [comment] 2022-07-18 16:20
Attached is a movie that shows the issue. When the application comes up there are 4 windows. The "main" widow and three "view" windows. View windows 2, 5, and 6 are obscured by the main window. All three windows are on top of each other.

I raise view window 2.  At 9 seconds I move it over one of the view windows that is obscured. I have no idea if it is view window 5 or 6.  I then move the window around to show normal docking options. 

At 29 seconds I attempt to dock view window 2 to the obscured window. It does not dock but hangs until I move it again (minor issue). At 39 seconds I attempt to dock view window 2 to the obscured window again. This time it docks. And view window 6 is raised with view window 2 docked. When I submitted my initial issue view window 6 was not being raised. Today it is being raised. 

Regardless, I do not think the obscured windows should show their docking. In my case there were two obscured windows 5 and 6. The user would not which window.

https://user-images.githubusercontent.com/26089249/179554500-1ca2ed6d-a4f7-4475-94b7-534702275fa9.mov

**Comment by ARSanderson** [comment] 2022-07-18 16:37
Here another example using the ADS demo. Undock all labels so to be three windows one above each other plus the calendar and place all of the other windows into a single tab. Reposition the main window over the labels so they are all obscured (beginning of the movie). Now drag the calendar around. The docking for the labels come up though they are obscured. I docked the calendar with one of the obscured labels but in this case it was not raised after being docked.

https://user-images.githubusercontent.com/26089249/179559551-859fd859-3ee7-4840-a2d3-7f9624c5179a.mov

**Comment by githubuser0xFFFF** [comment] 2022-07-18 19:04
Thank you for the videos - I understand the issue now. Unfortunately this problem is not reproducible on Windows 10 and Ubuntu Linux 20.04 because the floating DockWidgets are always in front of the main window. That means, the main Window will never obscure any floating window.

So I'm afraid you need to fix this issue by yourself. A pull request would be great.

**Comment by githubuser0xFFFF** [comment] 2022-07-20 06:24
The functions that update the drop overlays are 

- `FloatingDragPreviewPrivate::updateDropOverlays` and 
- `FloatingDockContainerPrivate::updateDropOverlays`

**Comment by rolivav** [comment] 2022-07-20 08:52
I think it might have something to do with this fix I added, maybe setting the active window also before updating the overlays would fix it? Don't have the time to look into it :/
```cpp
//============================================================================
void CFloatingDockContainer::moveEvent(QMoveEvent *event)
{
	QWidget::moveEvent(event);
	switch (d->DraggingState)
	{
	case DraggingMousePressed:
		d->setState(DraggingFloatingWidget);
		d->updateDropOverlays(QCursor::pos());
		break;

	case DraggingFloatingWidget:
		d->updateDropOverlays(QCursor::pos());
		// In OSX when hiding the DockAreaOverlay the application would set
		// the main window as the active window for some reason. This fixes
		// that by resetting the active window to the floating widget after
		// updating the overlays.
		QApplication::setActiveWindow(this);
		break;
	default:
		break;
	}
}
```

**Comment by githubuser0xFFFF** [comment] 2022-10-27 20:10
@ARSanderson Is there any progress with this issue or can I close it. Could you please test. if the normal QDockWidgets are always in front of the main winfow. Maybe it is an option to switch to QDockWidget as base class like it is done in Linux.

**Closed** 2022-11-13 10:44 UTC
Labels: help wanted, macOS
