### ISSUE TITLE
Crash if Floating Window is Docked, and then Undocked Quickly

### ISSUE THREAD

**Issue by jz-123** [githubuser0xFFFF/Qt-Advanced-Docking-System#86] opened 2019-12-09 16:55 UTC
Hi,

I have found an issue where I dock a window and then undock it quickly, it will crash.  I have tried to reproduce in the demo app, but was unable to.  I believe this is related to timing (I will explain further below) - my application is much more complex and has more interconnected signals/slots etc.

I am building in MSVC 2015, and have tested this in DEBUG and Release x64.

The crash occurs in the DockAreaTabBar::mouseMoveEvent, on the following lines of code:

```
if (d->FloatingWidget)
{
    d->FloatingWidget->moveFloating();
    return;
}
```

While debugging I see that d->FloatingWidget is non-null, but is a deleted pointer (the crash occurs on the moveFloating() call).

While tracing through the code, I see that the FloatingWidget is subject to a "deleteLater()" call when it is docked.   I (temporarily) connected a slot to the FloatingWidget "destroyed()" signal, and using tracepoints was able to determine that there are rare instances when the signal is emitted that the widget is not yet null.  These instances resulted in the crash on the lines above. 

Here are 2 potential fixes to this:
1) connect a slot to the FloatingWidget "destroyed()" signal which will check for null, and if it isn't it should disconnect the slot and set the pointer null. (I have tested this approach and no longer got any crashing).
```
void CDockAreaTabBar::onFloatingWidgetDestroyed(QObject* obj)
{
   if (d->FloatingWidget)
   {
      CFloatingDockContainer* floatDock = dynamic_cast<CFloatingDockContainer*>(d->FloatingWidget);
      if (floatDock)
      {
         disconnect(floatDock, SIGNAL(destroyed(QObject*)), this, SLOT(onFloatingWidgetDestroyed(QObject*)));
      }
      else
      {
         CFloatingOverlay* floatOverlay = dynamic_cast<CFloatingOverlay*>(d->FloatingWidget);
         if (floatOverlay)
         {
            disconnect(floatOverlay, SIGNAL(destroyed(QObject*)), this, SLOT(onFloatingWidgetDestroyed(QObject*)));
         }
      }
      d->FloatingWidget = nullptr;
   }
}
```

2) Change the functions which call "deleteLater()" to pass the floating widget pointer by ref (or as a double pointer) and assign the FloatingWidget null after calling delete later.

I should also note that it is possible that other widgets that get "deleteLater()" called on them may be subject to a similar timing related crash, so it may be worth looking at making them robust as well.

Thanks,

Jon

**Comment by githubuser0xFFFF** [comment] 2019-12-10 11:06
Thank you for your bug report. What do you mean with "I dock a window and then undock it quickly". That means you dock it and then undock it manually incredibly quick?

The **CDockAreaTabBar::mouseMoveEvent** handles the movement of the floating widget only if a dock area has just been undocked. If a mouse release event occurs, then the FloatingDockContainer acts as an event filter. That means it will receive the event and calls **FloatingDockContainerPrivate::titleMouseReleaseEvent**. But it does not filter out the event because the filter function returns false. That means, immediatelly after the filter has been called, the **CDockAreaTabBar::mouseReleaseEvent** function will be called. You can verify this with trace messages.

In the **CDockAreaTabBar::mouseReleaseEvent** function there is the following line: **d->FloatingWidget = nullptr**. So it is impossible that there is a mouse move event between **FloatingDockContainerPrivate::titleMouseReleaseEvent** and **CDockAreaTabBar::mouseReleaseEvent**. 

So in my opinion, this is impossible - so this is quite strange.

**Comment by jz-123** [comment] 2019-12-10 14:40
Hi,

> What do you mean with "I dock a window and then undock it quickly". That means you dock it and then undock it manually incredibly quick?

Yes I mean that I hover the FloatingWidget over the section I intend to drop it in, then as soon as I release the mouse I click where the top of where the window would be and drag the widget out of the area. I think it is actually grabbing the existing FloatingWindow before it docks (and before it is properly cleaned up, but after it has been deleted), not the docked one.

I found this quite by accident while I was showing ADS off to a colleague, and accidentally spazzed on clicking the mouse when I went to drop the window.  As I mentioned our application has alot going on in terms of the main UI thread which is why I believe it to be a rare timing issue.

I was able to get the demo to crash by adding two large size QTableWIdgets.  Each has 5 columns and a million rows.

Table creation function:
```
//============================================================================
static ads::CDockWidget* createTableWidget(QMenu* ViewMenu)
{
   static int TableCount = 0;
   QTableWidget* w = new QTableWidget();
   ads::CDockWidget* DockWidget = new ads::CDockWidget(QString("Table %1").arg(TableCount++));
   static int colCount = 5;
   static int rowCount = 1000000;
   w->setColumnCount(colCount);
   w->setRowCount(rowCount);
   for (int col = 0; col < colCount; ++col)
   {
      w->setHorizontalHeaderItem(col, new QTableWidgetItem(QString("Col %1").arg(col+1)));
      for (int row = 0; row < rowCount; ++row)
      {
         w->setItem(row, col, new QTableWidgetItem(QString("T %1-%2").arg(row + 1).arg(col+1)));
      }
   }
   DockWidget->setWidget(w);
   DockWidget->setToggleViewActionMode(ads::CDockWidget::ActionModeShow);
   ViewMenu->addAction(DockWidget->toggleViewAction());
   return DockWidget;
}
```
And added this to MainWindowPrivate::createContent():

```
...
    DockManager->addDockWidget(ads::CenterDockWidgetArea, createLongTextLabelDockWidget(ViewMenu), BottomDockArea);

   DockManager->addDockWidget(ads::CenterDockWidgetArea, createTableWidget(ViewMenu), RighDockArea);
   DockManager->addDockWidget(ads::CenterDockWidgetArea, createTableWidget(ViewMenu), BottomDockArea);

    // Test creation of floating dock widgets
    DockWidget = createFileSystemTreeDockWidget(ViewMenu);
...
```

It took me many tries to get it to crash but I was able to in the end.  I set up many docked widgets in a single "column" so that they are small.  I then take one and add it to the "right dock area" of one of the existing (docked) widgets. When I "drop" the Floating Widget, the mouse is already aligned and in position to grab the window.  I release the mouse, then click and move the mouse quickly.

Here are some screenshots.
![image](https://user-images.githubusercontent.com/17996598/70539037-12254000-1b31-11ea-9dda-ca4c96573e04.png)

Error Message:
![image](https://user-images.githubusercontent.com/17996598/70538147-9e366800-1b2f-11ea-9212-d12414c82d9f.png)

Debug inspection of the FloatingWidget:
![image](https://user-images.githubusercontent.com/17996598/70538252-c7ef8f00-1b2f-11ea-9994-902587854549.png)

**Comment by githubuser0xFFFF** [comment] 2019-12-13 10:57
I just created a new branch dock_undock_drash_fix and commited changes (02143ea) that should fix your crash issue.

Please test the branch a tell me if the problem is still there.

Thank you.

**Comment by githubuser0xFFFF** [comment] 2019-12-13 20:11
I merged the change into master. Should be fixed now with commit 02143ea

**Closed by githubuser0xFFFF** 2019-12-13 20:11 UTC
Labels: question

**Comment by jz-123** [comment] 2019-12-16 14:33
Hi,

I am still able to reproduce the error (have seen the crash in two locations):

![image](https://user-images.githubusercontent.com/17996598/70818549-012f3580-1da2-11ea-9b8d-b264d38a1493.png)

![image](https://user-images.githubusercontent.com/17996598/70914703-8145dd00-1fe6-11ea-922e-fe031280f226.png)

The error is occurring much less frequently, and is harder to produce.

The 2 solutions I posted earlier (essentially setting FloatingWidget = nullptr; immediately following the FloatingWIdget->deleterLater(); call, have not produced a crash in my testing).

Thanks,

Jon

**Comment by githubuser0xFFFF** [comment] 2019-12-16 14:55
Hi Jon,

II think this is a problem of your application or you running out of memory. If I create only two floating widgets with 1000000 rows, then my application crashes because it runs out of memory.
