### ISSUE TITLE
Demo stuck when trying to dock a floating window

### ISSUE THREAD

**Issue by vallsv** [githubuser0xFFFF/Qt-Advanced-Docking-System#431] opened 2022-06-18 19:54 UTC
Hi,

I am using pyqtads 3.8.2, with python 3.7 and Debian 10.

The application looks to stuck always when i try to dock a floating window.
I try to dock it back using the overlay icons.

It enforce to close the application.

**Comment by githubuser0xFFFF** [comment] 2022-06-19 07:03
Python was a third party contribution, so I'm not able to fix it

**Comment by vallsv** [comment] 2022-06-20 06:37
Args. Sad. Any idea if you have the same behaviour in C++?

**Comment by githubuser0xFFFF** [comment] 2022-06-20 06:55
I just tested the demo on Ubuntu 20.04 and do not see this issue

**Comment by ARSanderson** [comment] 2022-07-14 18:24
I am running on OS X and have seen this behavior intermittently. The window being moved become stuck and will not move.

I am usually able to unstick the windows by closing the one of the other application windows or shifting the focus to another application. A few times I have had to close the window.

**Comment by bjb-work** [comment] 2022-07-29 16:43
I'm getting something similar to what is mentioned in this thread, but it only happens in docker (Ubuntu 20.04, x11 forwarding). It happens when a floating window is grabbed, moved slightly, let go, and repeat (usually happens about the 3rd time, but sometimes more). I find that it happens more often when you move it between different dock areas before letting it go, but it can happen either way. I wonder if it's not getting a signal from my system that the mouse was released...

Anyways, this is what it looks like when it's stuck. Can't interact with any widgets inside the bigger window, not even if it's a floating window or even another application entirely. It goes back to normal if you move or resize the dock being moved in order to freeze it, but that's only possible if part of the window sits outside the bigger box.

Sometimes switching focus to another application and then back to the ADS application fixes the freeze.

![Screenshot from 2022-07-29 11-12-34](https://user-images.githubusercontent.com/109152723/181805152-69bf4e2b-6938-4437-af30-d4885613462a.png)

**Comment by STX321** [comment] 2022-08-31 03:34
> I'm getting something similar to what is mentioned in this thread, but it only happens in docker (Ubuntu 20.04, x11 forwarding). It happens when a floating window is grabbed, moved slightly, let go, and repeat (usually happens about the 3rd time, but sometimes more). I find that it happens more often when you move it between different dock areas before letting it go, but it can happen either way. I wonder if it's not getting a signal from my system that the mouse was released...
> 
> Anyways, this is what it looks like when it's stuck. Can't interact with any widgets inside the bigger window, not even if it's a floating window or even another application entirely. It goes back to normal if you move or resize the dock being moved in order to freeze it, but that's only possible if part of the window sits outside the bigger box.
> 
> Sometimes switching focus to another application and then back to the ADS application fixes the freeze.
> 
> ![Screenshot from 2022-07-29 11-12-34](https://user-images.githubusercontent.com/109152723/181805152-69bf4e2b-6938-4437-af30-d4885613462a.png)

I encountered the same proble，do you have resolved the problem?

**Comment by githubuser0xFFFF** [comment] 2022-08-31 04:43
I cannot reproduce this on Ubuntu 20.04

**Comment by githubuser0xFFFF** [comment] 2022-11-20 09:27
I close this issue, because nobody seems willing to fix this since 2 months and I cannot reproduce it on Ubuntu 20.04.

**Closed by githubuser0xFFFF** 2022-11-20 09:27 UTC
Labels: help wanted, Linux
