### ISSUE TITLE
Keep specific docks at constant size when inserting new docks

### ISSUE THREAD

**Issue by ix07** [githubuser0xFFFF/Qt-Advanced-Docking-System#236] opened 2020-08-10 19:15 UTC
Hi.

First of all I want to thank you for making this great piece of software - Kudos! We are currently adding it to our application and my boss wants to have a specific behavior when adding new docks.

Example:
- one dock left
- one dock area in the center
- one dock right

The behavior he wants, is, that when adding new docks to the center area (this is done programmatically) the other docks positioned to the sides (left/right) should keep the original sizes. The center dock(s) previously added should shrink to make room for the newly added dock. 

Here are two screenshots to illustrate this:

![s1](https://user-images.githubusercontent.com/29256437/89816136-49c40c00-db46-11ea-9af4-7ca41aff5f09.png)
![s2](https://user-images.githubusercontent.com/29256437/89816143-4c266600-db46-11ea-8abb-2fe1c908a9fb.png)

In "s1" the left and right dock have a specific width which should not be changed when adding a new dock.
In "s2" a new dock has been added in the center area and as you can see the left and right docks have shrunken in their width.

- Is this intended behavior? 
- Can this be avoided somehow?
- If this is intended behavior and cannot be avoided - could a flag be added to support a fixed dimension (width/height)
- Is there a way to manipulate the sizing logic allowing for the left and and right area docks to stay at a constant width while shrinking the center area?

I realize that the described situation is somewhat special, but a general solution or better understanding would also help a lot (can the sizing of the docks be manipulated?).

Thanks!

**Comment by githubuser0xFFFF** [comment] 2020-08-18 13:26
I cannot reproduce the problem in the demo application. If I have a left and center and a right dock are and insert a dock widget in the center area, then the center area will be split into two equal areas and the left and right dock areas remain at the same size.

**Comment by ix07** [comment] 2020-08-18 18:42
I converted my testing Visual Studio project into a creator project so you can just drop it into the "examples" sub directory of the ADS project. I hope I didn't make any mistakes (please forgive me if I did).

[adsTest.zip](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/files/5092197/adsTest.zip)

I already donated some Eurones to support your great work and will do so again (regardless of if this can actually be solved). As far as I know, my boss also contacted you to find out if you are interested in fixing/extending the library and actually being paid for that work.

Thanks!

**Comment by githubuser0xFFFF** [comment] 2020-08-19 08:50
I tested your example and can reproduce the behaviour. This is the sizing how it is implemented right now. If you drop a widget via mouse, then the target dock area will keep its size and will be split, if you insert the widget manually like you do, then you see the described behaviour.

**Comment by ix07** [comment] 2020-08-19 11:08
Thanks for confirming, but is there anything I can do, do modify this behavior? Consider a user has carefully arranged his dock layout, setting specific sizes for the left and right areas, and then those sizes change because he added a new dock into the center area. I think what we want to achieve is the same, as described in "Issue #199" - an area in which new document tabs/docks appear, but which does not grow when inserting new docks. Is this achievable? Thanks.

**Comment by githubuser0xFFFF** [comment] 2020-08-19 11:18
This is not a big issue. We have a commercial application that works with ADS since years and there was no single feedback from any user that a new window destroys a "carefully arranged" dock layout. So I thinks this is something you should not be afraid of.

**Comment by ix07** [comment] 2020-08-19 11:24
Well - ok, I would agree that this is a cosmetic issue and not really "destroying" his layout, but many users would find that behavior very annoying. Take the Visual Studio IDE as an example - consider you have set sizes for the "Solution Explorer" on the left side and some other docks on the right side. Now you split the code editor horizontally to display its contents side by side - with ADS the "Solution Explorer" on the left and the other docks on the right side would now shrink. After removing the split you would have a different layout then before and you would have to resize the docks back to the original state. Wouldn't you agree that this can become very annoying quickly? Everytime I split a document I have to restore my original layout.

**Comment by githubuser0xFFFF** [comment] 2020-08-19 11:30
Yes, maybe you are right. But there won't be any quick fix for this in the near future. Maybe you can checkout this docking implementation:

https://www.devmachines.com/qtitandocking-overview.html

Maybe they do not have this issue. Sorry that I cannot help you but I simply do not have the time for this change.

**Comment by ix07** [comment] 2020-08-19 11:37
I fully understand. Thank you for taking the time to investigate this.

**Comment by githubuser0xFFFF** [comment] 2020-08-19 11:43
Maybe you can modify the code. Like I wrote in the comments above, if the dock widget is drag and dropped via mouse, then it works exactly the way you want. So there must be code in the drop function that may be used for the insert function to get the same results.

**Comment by ix07** [comment] 2020-08-19 12:26
Thank you. We really appreciate your work. Thanks again!

**Comment by ix07** [comment] 2023-02-03 23:18
We found a workaround for this problem some time ago - maybe this can be useful to others.

A solution can be to put a *second* dock manager into a central dock widget - problem solved. The docks of both managers cannot be mixed, but in this case this is actually a good thing. The central dock will not grow because the splitting behavior of the inner docks will not affect it.

**Closed** 2024-05-10 12:20 UTC
Labels: help wanted, feature request
