### ISSUE TITLE
Missing Font Init Crash

### ISSUE THREAD

**Issue by Madrich** [githubuser0xFFFF/Qt-Advanced-Docking-System#568] opened 2023-10-05 08:11 UTC
Hi,
when try to float a dockwidget i get the following warning and crash.
`W: DirectWrite: CreateFontFaceFromHDC() failed (Gibt einen Fehler in einer Eingabedatei an, zum Beispiel eine Schriftartdatei.) for QFontDef(Family="8514oem", pointsize=8.25, pixelsize=20, styleHint=5, 
weight=400, stretch=100, hintingPreference=0) LOGFONT("8514oem", lfWidth=0, lfHeight=-20) dpi=96`
It seams like a more general problem with Qt and fonts, and not set them properly.
Any Idea?

**Comment by Madrich** [comment] 2023-10-05 08:49
I investigated more. It seams that this happens only if I make the 125% scale settings in windows.
Anybody with a solution for that?

**Comment by githubuser0xFFFF** [comment] 2023-10-06 04:50
I close this issue because it is not related to the Advanced Docking System. I tested with the demo application with 125% scaling and cannot reproduce the problem on Windows. So it seems to be related to the content in youd dorck widget.

**Closed by githubuser0xFFFF** 2023-10-06 04:50 UTC
