### ISSUE TITLE
Linux Mint 18.3: Segfault in "simple" example when clicking "detach group" button

### ISSUE THREAD

**Issue by steingrimsson** [githubuser0xFFFF/Qt-Advanced-Docking-System#213] opened 2020-06-30 04:21 UTC
The segfault happens in CFloatingDockContainer::startFloating() function on the line that calls show();
QT version 5.6.1. OS version is Linux Mint 18.3 Sylvia. g++ version 5.5.0. No errors or warnings during build in QT. The docking functionality works alright, just the "detach group" button segfaults in all examples.

**Comment by githubuser0xFFFF** [comment] 2020-06-30 05:55
Hi, I just tested ADS 3.5.1 on the following Linux systems:

- Ubuntu 20.04, Qt 5.12.8, gcc 9.3.0
- Kubuntu 19.10, Qt 5.12.4, gcc 9.2.1

I could not reproduce the problem. Detach group works without any problems. I do nt have any other Linux VMs here, so I think you need to narrow the problem down by yourself - sorry.

**Comment by githubuser0xFFFF** [comment] 2020-07-07 12:41
Are there any new findings or can I close this issue?

**Closed** 2020-07-14 09:17 UTC
Labels: Linux, help wanted
