### ISSUE TITLE
Force focus of current CDockWidget

### ISSUE THREAD

**Issue by dail8859** [githubuser0xFFFF/Qt-Advanced-Docking-System#216] opened 2020-07-03 19:25 UTC
### Desired Behavior
I am creating a multi-tabbed text editor based on this library. My desire is to have behavior like Visual Studio. When you click a tab, it will immediately focus the text area and the user can start typing immediately, they never have to actually click inside the text area.

---

I am trying to recreate this behavior, and as a simple test case I have been using the `deleteonclose` example. I am adding this to the main.cpp file

```c++
    QObject::connect(dockManager, &ads::CDockManager::focusedDockWidgetChanged, [] (ads::CDockWidget* old, ads::CDockWidget* now) {
        qDebug() << now->objectName();
        now->widget()->setFocus();
    });
```

However this only works when you switch between Dock Areas. (I'm assuming it is because it I am trying to change the focused widget inside of a `QApplication::focusChanged()` signal perhaps? not sure). It does not work when switching between tabs in the same area. Example:

![focus](https://user-images.githubusercontent.com/3694843/86493132-5a5eb680-bd3e-11ea-840e-aec1a560b248.gif)

---

My next attempt was using this instead:

```c++
    QObject::connect(dockManager, &ads::CDockManager::dockAreaCreated, [] (ads::CDockAreaWidget* DockArea) {
        qDebug() << "Dock Area Created";
        QObject::connect(DockArea, &ads::CDockAreaWidget::currentChanged, [=] (int index) {
            auto dockwidget = DockArea->dockWidget(index);
            qDebug() << dockwidget->objectName();
            dockwidget->widget()->setFocus();
        });
    });
```

However this does not send a signal when switching between dock areas since the index doesn't actually change, which after thinking about how this works I agree this is expected behavior:

![focus2](https://user-images.githubusercontent.com/3694843/86493630-3b612400-bd40-11ea-96be-31dbdce1731c.gif)

---

### Therefore...

My question is: Is there some way to get the behavior I desire? (Either by using existing signals or some way to subclass the existing classes?)

Or is this feature something that would have to be added to the core library, and if so is this something you would find useful to add?

**Comment by githubuser0xFFFF** [comment] 2020-07-03 21:29
The problem is, that the DockWidget is not yet visible when the `focusedDockWidgetChanged` signal is emitted. You can easily test this by writing the return value of `isVisible` to qDebug.

I improved this in branch https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/tree/focus_changed_fix. Please test - the focus changed signal is deferred until the dock widget is visible. This should improve the situation.

**Comment by dail8859** [comment] 2020-07-03 21:46
Thank you so much for looking into this so quickly!

I will try this new branch in the next day or so and report back.

**Comment by dail8859** [comment] 2020-07-04 15:41
Excellent! This seems to mostly solve the issue as expected.

There are two cases that it does not work (this behavior may have always existed prior to this fix). 

1. When there is a floating window, the background widget gets styled correctly, but does not get focus (not sure if this is a limitation of Qt since there is a window that is forced on top)
2. When dropping a floating window, it does not regain the focus.

See this example:

![focusfloat](https://user-images.githubusercontent.com/3694843/86515934-b41cba80-bdea-11ea-94e0-7d9281b48067.gif)

**Comment by githubuser0xFFFF** [comment] 2020-07-06 06:25
Improved this with commit #8cf41341256c903b5c5cf74456a8f601a15de924, please test.

**Comment by dail8859** [comment] 2020-07-06 22:57
Thanks for the latest update! Everything is working as expected.

The only one minor thing I noticed is that clicking on the tab will cause the `focusedDockWidgetChanged()` signal to get sent twice. Don't know if this is easy to address or not but I don't see this as much of an issue since my use case does not involve any heavy processing when switching tabs, however if others use this signal it might be good to document this behavior.

**Comment by githubuser0xFFFF** [comment] 2020-07-07 12:40
Improved this with commit 9974256d714d07deb23be3894a57661f152b6b7d. Please test.

**Comment by dail8859** [comment] 2020-07-07 23:08
Thanks again for the update! I found a few corner cases where it isn't behaving correctly.

Please don't think that I am just trying to find problems, I have just been testing it thoroughly. If you feel these are too obscure of a case to fix, then I understand and am fine with the current changes you have made.

---

When closing a non-focused tab, the current tab loses input focus.

1. Create two tabbed widgets
1. Type into the 2nd widget
1. Click on the `x` on the first tab to close it
1. Continue typing...and nothing happens

![lostfocus](https://user-images.githubusercontent.com/3694843/86853709-0b3dbc00-c085-11ea-9aff-546e1b7f103e.gif)

---

I also ran into a similar situation when closing the last tab of a dockarea, though I have not been able to reproduce it consistently yet.

**Comment by githubuser0xFFFF** [comment] 2020-07-08 06:14
Thanks for your extensive testing - it helps me a lot to find hidden bugs.

I improved this now. Please test again.

**Comment by dail8859** [comment] 2020-07-09 01:43
Again excellent work! One last caveat that I'm not sure is worth fixing. 

When the last `CDockWidget` is closed in a `CDockAreaWidget`, then no other widgets get the focus. 

![lostfocus](https://user-images.githubusercontent.com/3694843/86986905-c38d6200-c162-11ea-94aa-a134a64ccfda.gif)

I doubt the `CDockManager` keeps a running list of the last recently used `CDockAreaWidget`s so that it can focus the previously used area (and handle cases of multiple dockareas getting closed in a row), so it probably best left up to the user of this library to handle this case and monitor when `CDockAreaWidget` gets removed (is there a signal for this?) and then figure out what to do.

**Comment by rolivav** [comment] 2020-07-09 14:12
Maybe setting the tab order to CDockWidgets would work https://doc.qt.io/qt-5/qwidget.html#setTabOrder, but it is difficult to manage in my experience, you need to update it continuously. A better way is to reimplement https://doc.qt.io/qt-5/qwidget.html#focusNextPrevChild and use parentage to decide what happens with the focus but it takes a while to get right. At least it can be easily unit tested.

**Comment by githubuser0xFFFF** [comment] 2020-07-13 08:59
Merged into master - thank you for testing.

**Closed by githubuser0xFFFF** 2020-07-13 08:59 UTC
Labels: under review

**Comment by dail8859** [comment] 2020-07-13 12:19
Thanks for all the support!
