### ISSUE TITLE
All content becomes black when dragging a docking widget

### ISSUE THREAD

**Issue by SleepProgger** [githubuser0xFFFF/Qt-Advanced-Docking-System#220] opened 2020-07-07 03:29 UTC
*Thanks for this nice library.*

When testing the demo, but also in the QT creator using the QT quick designer, all widgets turn black when dragging docking widgets.

![image](https://user-images.githubusercontent.com/1274039/86701468-566ab700-c012-11ea-8cfe-d9a2e76b5f13.png)

QT version: 5.14.2
Tested Qt-Advanced-Docking-System tags: 3.5.1 and 3.4.2
System: Manjaro stable with XFCE (in case that matters)

Please let me know any other information which might be useful for you.

**Comment by githubuser0xFFFF** [comment] 2020-07-07 05:35
Closing this issue because it is a duplicate of issue #95. Look into this issue - you will find a detailed explanation there. The reason is, that compositing is disabled for the window manager.

Please checkout the pull request #217 - Vitaly implemented a solution that should fix this. Please test its fix and report your experience to me. Thank you.

**Closed by githubuser0xFFFF** 2020-07-07 05:35 UTC
