### ISSUE TITLE
CDockAreaWidget::currentDockWidget crashes during removeDockWidget

### ISSUE THREAD

**Issue by DannyVlasenko** [githubuser0xFFFF/Qt-Advanced-Docking-System#543] opened 2023-08-02 13:34 UTC
### Bug report

Version info:

- qt-ads - head of master
- Windows 10 Pro 2H22 build 19045.3208
- CMake 3.23, VS generator
- MSVC v143 WinSDK version 10.0.22000.0

The crash happens in the `CDockAreaWidget::removeDockWidget` function in the line ` auto CurrentDockWidget = currentDockWidget();`. This is caused by a cast `qobject_cast<CDockWidget*>(d->ContentsLayout->widget(Index));` in `CDockAreaWidget::dockWidget`. The cast uses dangling/uninitialized pointer returned from `CDockAreaLayout::widget` because pointers in `CDockAreaLayout::m_Widgets` look uninitialized.
This crash happens only in rare circumstances with several UI layouts. Before this, I used the 3.8.3 version and faced another bug fixed [here](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/commit/6d8e396e92c1109272f7fdba3ec681c600a90169). That crash gone but the new one, I describe here persists in the current master branch.

**Comment by githubuser0xFFFF** [comment] 2023-08-03 14:05
Could you please check, if the Index given to `d->ContentsLayout->widget(Index)` is valid. That means it is `>= 0` and `<= m_Widgets->count()`?

**Comment by DannyVlasenko** [comment] 2023-08-04 09:05
Yep, it equals 0 while m_Widgets->count() is 2. But the widget pointers in m_Widgets seem to point to nowhere.

**Comment by githubuser0xFFFF** [comment] 2023-08-04 09:52
Strange

**Comment by githubuser0xFFFF** [comment] 2023-09-06 04:34
Is there some way to reproduce the issue with the demo application? I cannot reproduce the problem here and therefore going to close this bug within the next days, because I think it is related to your application somehow.

**Comment by githubuser0xFFFF** [comment] 2023-09-19 06:48
No repsonse from the user since 2 weeks - closing this issue

**Closed by githubuser0xFFFF** 2023-09-19 06:48 UTC
Labels: under review, information required
