### ISSUE TITLE
Wayland does not support QWindow::requestActivate()

### ISSUE THREAD

**Issue by PerBothner** [githubuser0xFFFF/Qt-Advanced-Docking-System#288] opened 2020-12-30 23:14 UTC
I tried running the example programs on Fedora Linux 34 using the default Gnome/Wayland window manager, and failed pretty badly.  I could re-arrange tabs, but otherwise moving windows just made them into top-level windows.

I saw various warnings:

    QSocketNotifier: Can only be used with threads started with QThread
    Warning: Wayland does not support QWindow::requestActivate() ((null):0, (null))

The latter repeated multiple times.  I usually end up with a Segmentation fault.

I am able to run other Qt5 applications, including by own Qt front-end for [DomTerm](https://domterm.org), which uses QWebEngine.  (I'm evaluating using this library for DomTerm, in place of an existing pure-JavaScript library.)

**Comment by PerBothner** [comment] 2020-12-30 23:34
A work-around is to set `XDG_SESSION_TYPE`.  For example:

     XDG_SESSION_TYPE=x11 ./AdvancedDockingSystemDemo

**Comment by githubuser0xFFFF** [comment] 2020-12-31 08:32
Thank you for reporting this problem. I have given up in fixing esoteric Linux related issues like this. Unfortunately, there is no such thing as a Linux operating system - there are only a variety of different distributions. So it is not possible to support "Linux". It is only possible to support a small subset of Linux distributions. ADS works with Ubuntu 20.04 and 18.04 and that is o.k. for me.

So if someone would like to step in to fix this - the source code is here.

**Comment by PerBothner** [comment] 2020-12-31 16:20
I understand you don't want to deal with this now, as there is a work-around, and it is possible the problem will be fixed by a future Qt or Wayland release.  That said, Fedora is hardly some esoteric distribution: It's the forward edge of Red Hat Linux, and Linux in general. Ubuntu already includes Wayland.  While it isn't the default yet, there is no question it will be sooner or later, as it will for most Linux distributions. The unpcoming WSL release will incorporate a Wayland "server". (I could also point out that Windows and MacOS also exist in different versions.)

I might take a look at the issue, though I am hardly an expert in either Qt or Wayland. Though probably first I'll try to have DomTerm make use of ADS, and see if it's a good solution. (It looks very nice so far.)

**Comment by PerBothner** [comment] 2021-01-05 03:01
The message is related to calls to `activateWindow`.  I commented out those calls in the code, which avoided the message, but the test programs don't work.  (The window appears but dragging a dockable doesn't work.)

It is possible things work better on Qt6, but I haven't had a chance to try that.

**Comment by AHSauge** [comment] 2022-08-12 17:57
> A work-around is to set `XDG_SESSION_TYPE`. For example:
> 
> ```
>  XDG_SESSION_TYPE=x11 ./AdvancedDockingSystemDemo
> ```

This fix doesn't work when compiling with Qt6. Instead, you should use `QT_QPA_PLATFORM=xcb`

Piling on to what @ssokolow wrote above: This is not going to be fixed in Qt as per [this comment](https://forum.qt.io/topic/90639/comparing-qt-widgets-app-under-gnome-wayland-using-platform-wayland-egl-to-xcb/8)

> > qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
>
> This means your window tried to grab focus in the compositor, which is not allowed in wayland. Don't create a bug for it, there's nothing we can do.

What I'm gathering is that this would need to be implemented some other way and/or through integration per compositor (the major ones being KWin, mutter and wlroots). Given that we're talking about transferring focus between windows within the same application, I feel this should be possible and/or a valid enough use case to work, but right now I don't know how to approach it.

**Comment by ssokolow** [comment] 2022-08-12 18:17
> What I'm gathering is that this would need to be implemented some other way and/or through integration per compositor (the major ones being KWin, mutter and wlroots). Given that we're talking about transferring focus between windows within the same application, I feel this should be possible and/or a valid enough use case to work, but right now I don't know how to approach it.

I could certainly imagine a Wayland protocol extension that allows transferring focus between different window handles created through the same Wayland socket.

**Comment by AHSauge** [comment] 2022-08-12 19:59
> > What I'm gathering is that this would need to be implemented some other way and/or through integration per compositor (the major ones being KWin, mutter and wlroots). Given that we're talking about transferring focus between windows within the same application, I feel this should be possible and/or a valid enough use case to work, but right now I don't know how to approach it.
> 
> I could certainly imagine a Wayland protocol extension that allows transferring focus between different window handles created through the same Wayland socket. It'd probably even be less controversial than GNOME's decision to refuse to support the server-side window decoration protocol in favour of forcing every application to either link against GTK or implement their own decorations which probably won't match.

I think what we're looking for might be [XDG activation](https://wayland.app/protocols/xdg-activation-v1) and [this example](https://invent.kde.org/apol/xdg-activation-test/-/tree/master). It's Qt 6.3, so I can't test this on my own machine yet, but I'm updating a VM to test this out. Looking at the Qt source code, it seems this might actually solve this issue entirely. I'm finding [this change](https://codereview.qt-project.org/c/qt/qtwayland/+/321246/8/src/client/qwaylandwindow.cpp) to be promising at least.

**Comment by AHSauge** [comment] 2022-08-13 11:40
So I got good news and I got bad news.

Good news: I can confirm Qt 6.3 is helping here. No more warning about `QWindow::requestActivate`. 

Bad news: The problem now is that any logic related to screen coordinates (not too surprisingly) doesn't work at all. So while you can detach stuff, re-attaching stuff doesn't work. Similarly, moving widgets around is extremely buggy. At best, you might find an attachment point at random

**Comment by PerBothner** [comment] 2022-08-13 12:49
It appears the "Wyaland way" to move things around to use a [postioner](https://wayland-book.com/xdg-shell-in-depth/positioners.html). Unfortunately, as you see the documentation is rather lacking. I don't know if there is a Qt inteface to positioners.

**Comment by PerBothner** [comment] 2022-08-13 13:06
In [DomTerm](https://github.com/PerBothner/DomTerm/) I use the drag and drop builtin to modern web browsers, using [my fork of GoldenLayout](https://github.com/PerBothner/golden-layout).  That seems to mostly work.

I also implemented a hybrid approach in Qt, using a combination of QWidgets and QWebEngineView.  An outer QWebEngineView contains the GoldenLayout UI as well as the window titlebar. Each subwindow has it own child QWebEngineView or more generally a child QWidget. This works pretty well. One possible downside is that it is rather resource-hungry, making use of QtWebEngineView, at least for the docking UI.  If you're using that anyway, it seems a reasonable option.

**Comment by AHSauge** [comment] 2022-08-13 14:49
> It appears the "Wyaland way" to move things around to use a [postioner](https://wayland-book.com/xdg-shell-in-depth/positioners.html). Unfortunately, as you see the documentation is rather lacking. I don't know if there is a Qt inteface to positioners.

Well, it's lacking since it's unofficial, draft documentation you're reading right there. There are other (also unofficial) sources covering [xdg_positioner](https://wayland.app/protocols/xdg-shell#xdg_positioner). The closest I'm getting in Qt is [QWaylandXdgPopup](https://doc.qt.io/qt-6/qwaylandxdgpopup.html), but that seems more for menus and other pop-ups, not moving individual windows around. It also corresponds to xdg_popup, so not the same thing. The Qt documentation itself doesn't seem to even reference xdg_positioner even though there clearly is _something_ [implementing it](https://github.com/qt/qtwayland/blob/811f060c37a58580e0697d0beb34a6f91efeeb41/src/compositor/extensions/qwaylandxdgshell.cpp#L1988)

**Comment by AHSauge** [comment] 2022-08-13 15:20
Searching more around, it seems this is not working in Qt right now
* https://bugreports.qt.io/browse/QTBUG-91483
* https://bugreports.qt.io/browse/QTBUG-87332
* https://bugs.kde.org/show_bug.cgi?id=453558

It seems to all cumulate down to this though
* https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/46

**Comment by tytan652** [comment] 2022-10-21 06:52
Wayland does not allow global positioning only relative and ADS seems to rely on global.

**Comment by githubuser0xFFFF** [comment] 2022-10-27 20:05
I close the issue because it is a Qt problem and not an ADS issue

**Closed by githubuser0xFFFF** 2022-10-27 20:05 UTC
Labels: help wanted, Linux, Qt-Bug
