### ISSUE TITLE
Dock Manager restore state performance issue

### ISSUE THREAD

**Issue by jonjenssen** [githubuser0xFFFF/Qt-Advanced-Docking-System#478] opened 2023-01-16 16:47 UTC
We have an automated regression test system that tests our software, and since the commits on Dec 9, 2022, the total test runtime has increased by a lot. A typical test run used to take 17 minutes before this commit. After the commit, the tests take 26 minutes. (Everything else is unchanged.)

Our software is using Qt5 (5.15) and the QtAdvancedDocking system (latest from master branch), and we have 10+ docking widgets on the sides with a central widget in the middle. The test run starts our main Qt-based application once, and then for each test resets the dock layout with the _CDockManager_ method _restoreState_ to start with a clean layout.  (The application itself is not restarted between each test. ) 

As more and more tests (60+) are run, the time spent in the method restoreState seems to increase, suggesting that there is something building up inside the dock manager that takes more and more time for each call to it. 

This seems to indicate that something inside the dock manager isn't doing what it is supposed to do, any idea what is wrong?

**Comment by githubuser0xFFFF** [comment] 2023-01-16 17:45
No, I have no idea - would be great (in the spirit of open source software), if you could find out what's going on.

**Comment by githubuser0xFFFF** [comment] 2023-01-19 07:42
I did a quick test with the latest master version to reproduce the problem. I added the following lines to the demo application (line 756):

```c++
	/*connect(d->PerspectiveComboBox, SIGNAL(activated(QString)),
		d->DockManager, SLOT(openPerspective(QString)));*/
	QTimer* t = new QTimer();
	connect(t, &QTimer::timeout, [t, this](){
		static int PerspectiveIndex = 0;
		static QVector<int> FirstOpenTime(d->PerspectiveComboBox->count(), 0);
		static int Count = 0;
		QString PerspectiveName = d->PerspectiveComboBox->itemText(PerspectiveIndex);
		std::cout << ++Count << " timeout " << PerspectiveName.toStdString() << std::endl;
		QElapsedTimer Timer;
		Timer.start();
		d->DockManager->openPerspective(PerspectiveName);
		auto Elapsed = Timer.elapsed();
		if (FirstOpenTime[PerspectiveIndex] < 1)
		{
			FirstOpenTime[PerspectiveIndex] = Elapsed;
		}
		std::cout << "Elapsed " << Elapsed << " [" << FirstOpenTime[PerspectiveIndex] << "]" << std::endl;
		PerspectiveIndex = (PerspectiveIndex + 1) % d->PerspectiveComboBox->count();
	});

	connect(d->PerspectiveComboBox, qOverload<const QString&>(&QComboBox::activated), [this, t](const QString& PerspectiveName){
		QElapsedTimer Timer;
		Timer.start();
		d->DockManager->openPerspective(PerspectiveName);
		this->setProperty("Perspective", PerspectiveName);
		std::cout << "Elapsed " << Timer.elapsed() << std::endl;
		t->start(1000);
	});
```
As soon as the first perspective change is requested by the user by selecting an item from the perspective ComboBox a timer is started with an intervall of 1000 ms that cycles through all perspectives in the ComboBox. The first perspective load time is recorded for each perspective in the **FirstOpenTime** vector. The **count** variable counts the number of perspective switches. I created a number of perspectives with docked, floating and pinned windows. These are the results (console output) after more than 1000 perspective switches:

```
1087 timeout Default3
Elapsed 572 [567]
1088 timeout Default4
Elapsed 481 [469]
1089 timeout Floating1
Elapsed 430 [434]
1090 timeout Label2Pinned
Elapsed 545 [536]
1091 timeout PinBottom
Elapsed 524 [532]
1092 timeout PinRight
Elapsed 512 [518]
1093 timeout PinTop
Elapsed 521 [522]
1094 timeout PinnedV1
Elapsed 469 [472]
1095 timeout PinnedV2
Elapsed 9 [8]
1096 timeout AutoHIdeLeft
Elapsed 512 [378]
1097 timeout AutoHideDemo
Elapsed 456 [359]
1098 timeout CrashTest
Elapsed 514 [408]
1099 timeout CrashTest2
Elapsed 539 [450]
1100 timeout Default
Elapsed 500 [434]
1101 timeout Default2
```

So there is no significant difference between the first loading time and the loading time after 1000 perspective changes. That means, I could not reproduce your issue. So it is likely a problem in your application and I will close this issue.

**Closed by githubuser0xFFFF** 2023-01-19 07:42 UTC
Labels: help wanted, information required

**Comment by githubuser0xFFFF** [comment] 2023-01-20 06:38
Btw. could you please send me a nice screenshot (1920 x 1080) of the ResInsight application, that shows that it uses the Advanced Docking System. I would like to have it on my showcase section. The screenshots in the web are always with the old Qt docking system. I downloaded and started the application but I do not have any sample data to generate a nice screenshot - something like this: https://resinsight.org/images/getting-started/ResInsightUIMediumSize.png
